/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JuegosMisericordia.AppJuegosMisericordia.ui.gestionProductos;

import JuegosMisericordia.AppJuegosMisericordia.services.GestorProductos;

/**
 *
 * @author Daniel
 */
public class FormularioEditarProducto extends javax.swing.JFrame {

    /**
     * Creates new form FormularioEditarEmpleado
     */

    String codigoAEditar;
    PanelGestionInventario panelGestion;
    public FormularioEditarProducto(String codigo, String nombre, double valorUnitario, int unidadesDisponibles, PanelGestionInventario panel) {
        initComponents();

        codigoField.setText(codigo);
        nombreField.setText(nombre);
        valorField.setText(String.valueOf(valorUnitario));
        stockField.setText(String.valueOf(unidadesDisponibles));

        panelGestion = panel;
        codigoAEditar = codigo;

        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        stockField = new javax.swing.JTextField();
        codigoField = new javax.swing.JTextField();
        valorField = new javax.swing.JTextField();
        cancelarBtn = new javax.swing.JButton();
        editarBtn = new javax.swing.JButton();
        nombreField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 400));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Edición de datos");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(210, 30, 192, 32);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Unidades en Stock");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(190, 260, 140, 19);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Código");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(190, 80, 60, 19);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Nombre");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(190, 140, 60, 19);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Valor Unitario");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(190, 200, 110, 19);
        jPanel1.add(stockField);
        stockField.setBounds(190, 280, 230, 30);
        jPanel1.add(codigoField);
        codigoField.setBounds(190, 100, 230, 30);
        jPanel1.add(valorField);
        valorField.setBounds(190, 220, 230, 30);

        cancelarBtn.setText("Cancelar");
        cancelarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBtnActionPerformed(evt);
            }
        });
        jPanel1.add(cancelarBtn);
        cancelarBtn.setBounds(340, 335, 110, 30);

        editarBtn.setText("Guardar cambios");
        editarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarBtnActionPerformed(evt);
            }
        });
        jPanel1.add(editarBtn);
        editarBtn.setBounds(170, 335, 120, 30);
        jPanel1.add(nombreField);
        nombreField.setBounds(190, 160, 230, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void editarBtnActionPerformed(java.awt.event.ActionEvent evt) {
        String codigo = codigoField.getText();
        String nombre = nombreField.getText();
        double valorUnitario = Double.parseDouble(valorField.getText());
        int unidadesDisponibles = Integer.parseInt(stockField.getText());

        GestorProductos gestor = new GestorProductos();

        gestor.actualizarDatos(codigoAEditar, codigo, nombre, valorUnitario, unidadesDisponibles);

        panelGestion.limpiarDatos();
        panelGestion.mostrarDatos();

        this.dispose();
    }

    private void cancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify
    private javax.swing.JButton cancelarBtn;
    private javax.swing.JTextField codigoField;
    private javax.swing.JButton editarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField nombreField;
    private javax.swing.JTextField stockField;
    private javax.swing.JTextField valorField;
    // End of variables declaration
}
