package JuegosMisericordia.ui;

import JuegosMisericordia.services.GestorAdministrador;
import JuegosMisericordia.services.GestorVendedor;
import JuegosMisericordia.model.Empleado;

public class FormularioAnadirEmpleado extends javax.swing.JFrame {
    PanelGestionEmpleados panelGestion;


    public FormularioAnadirEmpleado(PanelGestionEmpleados panel) {
        initComponents();

        this.setVisible(true);
        this.setLocationRelativeTo(null);
        panelGestion = panel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        salarioField = new javax.swing.JTextField();
        idField = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        buttonCancelar = new javax.swing.JButton();
        buttonAnadirVendedor = new javax.swing.JButton();
        buttonAnadirAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 500));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(700, 500));
        jPanel2.setLayout(null);
        jPanel2.add(salarioField);
        salarioField.setBounds(260, 290, 200, 30);
        jPanel2.add(idField);
        idField.setBounds(260, 110, 200, 30);
        jPanel2.add(nameField);
        nameField.setBounds(260, 170, 200, 30);
        jPanel2.add(passwordField);
        passwordField.setBounds(260, 230, 200, 30);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Identificación");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(260, 90, 110, 19);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Contraseña");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(260, 210, 110, 19);

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Formulario de registro");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(240, 30, 252, 32);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Salario");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(260, 270, 110, 19);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Nombre");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(260, 150, 110, 19);

        buttonCancelar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        buttonCancelar.setText("Volver");
        buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(buttonCancelar);
        buttonCancelar.setBounds(500, 420, 160, 40);

        buttonAnadirVendedor.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        buttonAnadirVendedor.setText("Registrar como vendedor");
        buttonAnadirVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAnadirVendedorActionPerformed(evt);
            }
        });
        jPanel2.add(buttonAnadirVendedor);
        buttonAnadirVendedor.setBounds(360, 350, 250, 29);

        buttonAnadirAdmin.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        buttonAnadirAdmin.setText("Registrar como administrador");
        buttonAnadirAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAnadirAdminActionPerformed(evt);
            }
        });
        jPanel2.add(buttonAnadirAdmin);
        buttonAnadirAdmin.setBounds(90, 350, 250, 29);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 700, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();
    }

    private void buttonAnadirVendedorActionPerformed(java.awt.event.ActionEvent evt) {
        GestorVendedor gestor = new GestorVendedor();

        String nuevoID = idField.getText();
        String nuevoNombre = nameField.getText();
        String nuevoPassword = passwordField.getText();
        double nuevoSalario = Double.parseDouble(salarioField.getText());

        Empleado vendedor = new Empleado(nuevoID, nuevoNombre, nuevoPassword, nuevoSalario, Empleado.ESTADO_ACTIVO, Empleado.ROL_VENDEDOR);

        gestor.addSeller(vendedor);

        idField.setText("");
        nameField.setText("");
        passwordField.setText("");
        salarioField.setText("");

        panelGestion.limpiarDatos();
        panelGestion.mostrarDatos();
    }

    private void buttonAnadirAdminActionPerformed(java.awt.event.ActionEvent evt) {
        GestorAdministrador gestor = new GestorAdministrador();

        String nuevoID = idField.getText();
        String nuevoNombre = nameField.getText();
        String nuevoPassword = passwordField.getText();
        double nuevoSalario = Double.parseDouble(salarioField.getText());

        Empleado admin = new Empleado(nuevoID, nuevoNombre, nuevoPassword, nuevoSalario, Empleado.ESTADO_ACTIVO, Empleado.ROL_ADMINISTRADOR);

        gestor.addAdmin(admin);

        idField.setText("");
        nameField.setText("");
        passwordField.setText("");
        salarioField.setText("");

        panelGestion.limpiarDatos();
        panelGestion.mostrarDatos();
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify
    private javax.swing.JButton buttonAnadirAdmin;
    private javax.swing.JButton buttonAnadirVendedor;
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField passwordField;
    private javax.swing.JTextField salarioField;
    // End of variables declaration
}