package JuegosMisericordia.ui;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import JuegosMisericordia.ui.gestionProductos.PanelGestionInventario;
import JuegosMisericordia.ui.informes.InterfazInformes;

import javax.swing.*;

/**
 * @author Daniel
 */
public class PanelAdmin extends javax.swing.JFrame {

    /**
     * Creates new form PanelAdmin
     */
    public PanelAdmin() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setResizable(false);
        ImageIcon img = new ImageIcon(getClass().getResource("/icono/iconoBarraJFrame.png"));
        this.setIconImage(img.getImage());
        this.setTitle("SIG - Juegos Misericordia V1.0 - Panel de Administrador");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttonGestionInventario = new javax.swing.JButton();
        buttonGenerarInformes = new javax.swing.JButton();
        buttonGestionEmpleados = new javax.swing.JButton();
        buttonLogOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Eras Demi ITC", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenido, seleccione una opción.");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 50, 630, 37);

        buttonGestionInventario.setBackground(new java.awt.Color(204, 204, 204));
        buttonGestionInventario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        buttonGestionInventario.setForeground(new java.awt.Color(0, 0, 0));
        buttonGestionInventario.setText("Gestionar Inventario");
        buttonGestionInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGestionInventarioActionPerformed(evt);
            }
        });
        jPanel1.add(buttonGestionInventario);
        buttonGestionInventario.setBounds(260, 120, 260, 80);

        buttonGenerarInformes.setBackground(new java.awt.Color(204, 204, 204));
        buttonGenerarInformes.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        buttonGenerarInformes.setForeground(new java.awt.Color(0, 0, 0));
        buttonGenerarInformes.setText("Generar Informes");
        buttonGenerarInformes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGenerarInformesActionPerformed(evt);
            }
        });
        jPanel1.add(buttonGenerarInformes);
        buttonGenerarInformes.setBounds(260, 320, 260, 80);

        buttonGestionEmpleados.setBackground(new java.awt.Color(204, 204, 204));
        buttonGestionEmpleados.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        buttonGestionEmpleados.setForeground(new java.awt.Color(0, 0, 0));
        buttonGestionEmpleados.setText("Gestionar Empleados");
        buttonGestionEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGestionEmpleadosActionPerformed(evt);
            }
        });
        jPanel1.add(buttonGestionEmpleados);
        buttonGestionEmpleados.setBounds(260, 220, 260, 80);

        buttonLogOut.setBackground(new java.awt.Color(0, 102, 102));
        buttonLogOut.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        buttonLogOut.setForeground(new java.awt.Color(255, 255, 255));
        buttonLogOut.setText("Cerrar Sesión");
        buttonLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogOutActionPerformed(evt);
            }
        });
        jPanel1.add(buttonLogOut);
        buttonLogOut.setBounds(540, 440, 222, 34);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>

    private void buttonGenerarInformesActionPerformed(java.awt.event.ActionEvent evt) {
        InterfazInformes interfazInformes = new InterfazInformes();
        this.dispose();
    }

    private void buttonLogOutActionPerformed(java.awt.event.ActionEvent evt) {
        int confirmacion = JOptionPane.showConfirmDialog(null, "¿Está seguro de que desea cerrar sesión?", "Cerrar Sesión", JOptionPane.YES_NO_OPTION);
        if (confirmacion == JOptionPane.YES_OPTION) {
            PestanaLogin pestanaLogin = new PestanaLogin();
            this.dispose();
        }
    }

    private void buttonGestionEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {
        PanelGestionEmpleados panelGestionEmpleados = new PanelGestionEmpleados();
        panelGestionEmpleados.setVisible(true);
        panelGestionEmpleados.setLocationRelativeTo(null);
        this.dispose();
    }

    private void buttonGestionInventarioActionPerformed(java.awt.event.ActionEvent evt) {
        PanelGestionInventario panelGestionInventario = new PanelGestionInventario();
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton buttonGenerarInformes;
    private javax.swing.JButton buttonGestionEmpleados;
    private javax.swing.JButton buttonGestionInventario;
    private javax.swing.JButton buttonLogOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration
}