package JuegosMisericordia.ui;

import javax.swing.*;

/**
 *
 * @author Daniel
 */
public class PestanaLogin extends javax.swing.JFrame {

    /**
     * Creates new form PestañaLogin
     */
    public PestanaLogin() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        Right = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        adminLoginButton = new javax.swing.JButton();
        sellerLoginButton = new javax.swing.JButton();
        salirBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(0, 204, 204));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel3.setLayout(null);

        Right.setBackground(new java.awt.Color(0, 102, 102));
        Right.setPreferredSize(new java.awt.Dimension(400, 500));
        Right.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Harlow Solid Italic", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Juegos Misericordia");
        Right.add(jLabel2);
        jLabel2.setBounds(43, 302, 299, 57);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/output-onlinepngtools(1).png"))); // NOI18N
        Right.add(jLabel4);
        jLabel4.setBounds(117, 119, 150, 150);

        jPanel3.add(Right);
        Right.setBounds(0, 0, 400, 500);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 500));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Bienvenido");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(119, 36, 160, 41);

        adminLoginButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        adminLoginButton.setText("Inicio de sesión Administradores");
        adminLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminLoginButtonActionPerformed(evt);
            }
        });
        jPanel1.add(adminLoginButton);
        adminLoginButton.setBounds(36, 173, 321, 58);

        sellerLoginButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        sellerLoginButton.setText("Inicio de sesión Vendedores");
        sellerLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellerLoginButtonActionPerformed(evt);
            }
        });
        jPanel1.add(sellerLoginButton);
        sellerLoginButton.setBounds(36, 296, 321, 58);

        salirBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/iconoSalir.png"))); // NOI18N
        salirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBtnActionPerformed(evt);
            }
        });
        jPanel1.add(salirBtn);
        salirBtn.setBounds(301, 406, 70, 70);

        jPanel3.add(jPanel1);
        jPanel1.setBounds(400, 0, 400, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void adminLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {
        VentanaLoginAdmin ventanaLoginAdmin = new VentanaLoginAdmin();
        ventanaLoginAdmin.setVisible(true);
        ventanaLoginAdmin.setLocationRelativeTo(null);
        this.dispose();
    }

    private void sellerLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {
        VentanaLoginVendedor ventanaLoginVendedor = new VentanaLoginVendedor();
        ventanaLoginVendedor.setVisible(true);
        ventanaLoginVendedor.setLocationRelativeTo(null);
        this.dispose();
    }

    private void salirBtnActionPerformed(java.awt.event.ActionEvent evt) {
        int confirmacion = JOptionPane.showConfirmDialog(null, "¿Está seguro de que desea salir de la aplicación?", null, JOptionPane.YES_NO_OPTION);
        if (confirmacion == JOptionPane.YES_OPTION){
            this.dispose();
        }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify
    private javax.swing.JPanel Right;
    private javax.swing.JButton adminLoginButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton salirBtn;
    private javax.swing.JButton sellerLoginButton;
    // End of variables declaration
}
